Hyperparameters:
  num_epochs: 10
  batch_size: 64
  val_batch_size: 256
  patience: 2
  num_workers: 4

Optimizer:
  name: Adam
  lr: 0.0005

Architecture:
  model_type: rec
  algorithm: STARNet
  Transform:
    name: TPS
    num_fiducial: 20
    loc_lr: 0.1
    model_name: large
  Backbone:
    name: ResNet
    layers: 34
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
    hidden_size: 256
  Head:
    name: CTCHead
    fc_decay: 0

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric

Dataset:
  name: TextRecognitionDataset
  image_height: 32
  image_width: 100
  preprocesses:
    - CTCLabelEncode:
        max_text_length: 80