Hyperparameters:
  num_epochs: 10
  batch_size: 64
  val_batch_size: 256
  patience: 2
  num_workers: 4

Optimizer:
  name: Adam
  lr: 0.0005

Architecture:
  model_type: rec
  algorithm: Rosetta
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead
    fc_decay: 0.0004

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric

Dataset:
  name: TextRecognitionDataset
  image_height: 32
  image_width: 100
  preprocesses:
    - CTCLabelEncode:
        max_text_length: 80