Hyperparameters:
  num_epochs: 10
  batch_size: 12
  val_batch_size: 1
  patience: 2
  num_workers: 4

Architecture:
  model_type: det
  algorithm: EAST
  Transform:
  Backbone:
    name: ResNet_vd
    layers: 50
  Neck:
    name: EASTFPN
    model_name: large
  Head:
    name: EASTHead
    model_name: large

Loss:
  name: EASTLoss

Optimizer:
  name: Adam
  lr: 0.001

PostProcess:
  name: EASTPostProcess
  score_thresh: 0.8
  cover_thresh: 0.1
  nms_thresh: 0.2

Metric:
  name: DetMetric
  main_indicator: hmean

Dataset:
  name: TextDetectionDataset
  image_height: 512
  image_width: 512
  tensor_keys: [ 'image', 'score_map', 'geo_map', 'training_mask' ]