Hyperparameters:
  num_epochs: 50
  batch_size: 12
  val_batch_size: 1
  patience: 2
  num_workers: 4

Architecture:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
    disable_se: True
  Neck:
    name: RSEFPN
    out_channels: 96
    shortcut: True
  Head:
    name: DBHead
    k: 50

Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3

Optimizer:
  name: Adam
  lr: 0.001

PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5

Metric:
  name: DBMetric

Dataset:
  name: TextDetectionDataset
  image_height: 960
  image_width: 960
  preprocesses:
    - MakeBorderAndShrinkMap:
  tensor_keys:
    - image
    - shrink_map
    - shrink_mask
    - threshold_map
    - threshold_mask