Hyperparameters:
  num_epochs: 10
  batch_size: 64
  val_batch_size: 256
  patience: 2
  num_workers: 4

Optimizer:
  name: AdamW
  betas: 0.9, 0.99
  eps: 0.00000008
  weight_decay: 0.05
  lr: 0.0003

Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
    name: STN_ON
    tps_inputsize: [ 32, 64 ]
    tps_outputsize: [ 32, 320 ]
    num_control_points: 20
    tps_margins: [ 0.05,0.05 ]
    stn_activation: none
  Backbone:
    name: SVTRNet
    img_size: [ 32, 320 ]
    out_char_num: 40
    out_channels: 192
    patch_merging: 'Conv'
    embed_dim: [ 64, 128, 256 ]
    depth: [ 3, 6, 3 ]
    num_heads: [ 2, 4, 8 ]
    mixer: [ 'Local','Local','Local','Local','Local','Local','Global','Global','Global','Global','Global','Global' ]
    local_mixer: [ [ 7, 11 ], [ 7, 11 ], [ 7, 11 ] ]
    last_stage: True
    prenorm: false
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric

Dataset:
  name: TextRecognitionDataset
  image_height: 64
  image_width: 256
  preprocesses:
    - CTCLabelEncode:
        max_text_length: 40